export const GET_ERRORS = "GET_ERROR";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const DELETE_PROJECT_TASKS = "DELETE_PROJECT_TASKS";